version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - run: npm rebuild node-sass --force
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: npm run build:lib
      - run: npm run build
      - run: npm run runall
